trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  Major: '1'
  Minor: '0'
  Patch: $[counter(format('{0}.{1}', variables['Major'], variables['Minor']), 0)]
  PackageVersion: '$(Major).$(Minor).$(Patch)'

steps:
- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'ApiClientGeneration/Candy.Api/Candy.Api.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/api'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'ApiClientGeneration\Candy.Api.Clients\Candy.Api.Clients.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'ApiClientGeneration\Candy.Api.Clients\Candy.Api.Clients.csproj'
    configuration: '$(buildConfiguration)'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'PackageVersion'
    packDirectory: $(build.artifactstagingdirectory)/client

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/api'
    ArtifactName: 'api'
    publishLocation: 'Container'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/client'
    ArtifactName: 'client'
    publishLocation: 'Container'
